version: "3"

services:
  nest:
    container_name: nestjs
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/nest
      - /nest/node_modules
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
